const users = [
  {
    username: "john_doe",
    image: "https://images.unsplash.com/photo-1",
    password: "Password123!",
    goals: ["Fitness", "Weight Loss"],
    preferences: ["Morning Workouts", "Outdoor Activities"],
    availability: "Weekends",
    mobile: 9876543210,
    gmail: "john.doe@gmail.com",
  },
  {
    username: "jane_smith",
    image: "https://images.unsplash.com/photo-2",
    password: "JaneDoe@2024",
    goals: ["Strength Training"],
    preferences: ["Evening Workouts", "Indoor Gym"],
    availability: "Evenings",
    mobile: 9876543211,
    gmail: "jane.smith@gmail.com",
  },
  {
    username: "mike_jordan",
    image: "https://images.unsplash.com/photo-3",
    password: "Mike@123",
    goals: ["Cardio", "Running"],
    preferences: ["Morning Runs", "Music During Workouts"],
    availability: "Mornings",
    mobile: 9876543212,
    gmail: "mike.jordan@gmail.com",
  },
  {
    username: "emily_clark",
    image: "https://images.unsplash.com/photo-4",
    password: "EmilyPass@456",
    goals: ["Yoga", "Flexibility"],
    preferences: ["Home Workouts", "Calm Environment"],
    availability: "Afternoons",
    mobile: 9876543213,
    gmail: "emily.clark@gmail.com",
  },
  {
    username: "david_wilson",
    image: "https://images.unsplash.com/photo-5",
    password: "David@789",
    goals: ["Muscle Gain"],
    preferences: ["Weight Lifting", "High-Intensity Workouts"],
    availability: "Evenings",
    mobile: 9876543214,
    gmail: "david.wilson@gmail.com",
  },
  {
    username: "sarah_jones",
    image: "https://images.unsplash.com/photo-6",
    password: "Sarah@2024",
    goals: ["Pilates"],
    preferences: ["Small Group Sessions", "Flexible Timings"],
    availability: "Flexible",
    mobile: 9876543215,
    gmail: "sarah.jones@gmail.com",
  },
  {
    username: "kevin_brown",
    image: "https://images.unsplash.com/photo-7",
    password: "Kevin@123",
    goals: ["Endurance Training"],
    preferences: ["Long-Distance Running", "Outdoor Cycling"],
    availability: "Weekends",
    mobile: 9876543216,
    gmail: "kevin.brown@gmail.com",
  },
  {
    username: "olivia_martin",
    image: "https://images.unsplash.com/photo-8",
    password: "Olivia@321",
    goals: ["Dance Fitness"],
    preferences: ["Zumba Classes", "Group Workouts"],
    availability: "Evenings",
    mobile: 9876543217,
    gmail: "olivia.martin@gmail.com",
  },
  {
    username: "chris_evans",
    image: "https://images.unsplash.com/photo-9",
    password: "Chris@456",
    goals: ["Bodybuilding"],
    preferences: ["Gym Training", "Protein-Rich Diet"],
    availability: "Mornings",
    mobile: 9876543218,
    gmail: "chris.evans@gmail.com",
  },
  {
    username: "emma_watson",
    image: "https://images.unsplash.com/photo-10",
    password: "Emma@789",
    goals: ["Meditation"],
    preferences: ["Peaceful Environment", "Guided Sessions"],
    availability: "Flexible",
    mobile: 9876543219,
    gmail: "emma.watson@gmail.com",
  },
];

module.exports = { data: users };
