const sampleRequestUsers = [
  {
    username: "shahrukh_khan",
    image: "https://example.com/images/shahrukh_khan.jpg",
    password: "srkKing123",
    goals: ["Acting Excellence", "Philanthropy"],
    preferences: ["Fitness", "Travel"],
    availability: "Weekends 10 AM - 4 PM",
    mobile: 9876543210,
    gmail: "shahrukh.khan@gmail.com",
  },
  {
    username: "amitabh_bachchan",
    image: "https://example.com/images/amitabh_bachchan.jpg",
    password: "bigBsecure456",
    goals: ["Versatile Acting", "Public Speaking"],
    preferences: ["Classic Music", "Books"],
    availability: "Daily 8 AM - 1 PM",
    mobile: 9123456789,
    gmail: "amitabh.bachchan@gmail.com",
  },
  {
    username: "UserX",
    image: "https://example.com/images/deepika_padukone.jpg",
    password: "deepikaPass789",
    goals: ["Fitness", "Mental Health Awareness"],
    preferences: ["Healthy Eating", "Yoga"],
    availability: "Flexible",
    mobile: 9234567890,
    gmail: "deepika.padukone@gmail.com",
  },
  {
    username: "prabhas",
    image: "https://example.com/images/prabhas.jpg",
    password: "prabhasStar123",
    goals: ["Pan-India Projects", "Adventure Sports"],
    preferences: ["Outdoor Activities", "South Indian Cuisine"],
    availability: "Weekends Only",
    mobile: 9345678901,
    gmail: "prabhas.actor@gmail.com",
  },
  {
    username: "UserY",
    image: "https://example.com/images/alia_bhatt.jpg",
    password: "aliaCute555",
    goals: ["Music", "Acting Growth"],
    preferences: ["Dance", "Animal Welfare"],
    availability: "Weekdays 5-7 PM",
    mobile: 9456789012,
    gmail: "alia.bhatt@gmail.com",
  },
  {
    username: "ranveer_singh",
    image: "https://example.com/images/ranveer_singh.jpg",
    password: "ranveerCool123",
    goals: ["Versatile Roles", "Fashion Trends"],
    preferences: ["Music", "Travel"],
    availability: "Flexible",
    mobile: 9567890123,
    gmail: "ranveer.singh@gmail.com",
  },
  {
    username: "hrithik_roshan",
    image: "https://example.com/images/hrithik_roshan.jpg",
    password: "hrithikFit456",
    goals: ["Dance Mastery", "Action Movies"],
    preferences: ["Gym Workouts", "Music"],
    availability: "Daily 6-8 AM",
    mobile: 9789012345,
    gmail: "hrithik.roshan@gmail.com",
  },
  {
    username: "nawazuddin_siddiqui",
    image: "https://example.com/images/nawazuddin_siddiqui.jpg",
    password: "nawazAct123",
    goals: ["Method Acting", "Realistic Roles"],
    preferences: ["Books", "Nature Walks"],
    availability: "Weekends Only",
    mobile: 9901234567,
    gmail: "nawazuddin.siddiqui@gmail.com",
  },
  {
    username: "david_wilson",
    image: "https://images.unsplash.com/photo-5",
    password: "David@789",
    goals: ["Muscle Gain"],
    preferences: ["Weight Lifting", "High-Intensity Workouts"],
    availability: "Evenings",
    mobile: 9876543214,
    gmail: "david.wilson@gmail.com",
  },
  {
    username: "sarah_jones",
    image: "https://images.unsplash.com/photo-6",
    password: "Sarah@2024",
    goals: ["Pilates"],
    preferences: ["Small Group Sessions", "Flexible Timings"],
    availability: "Flexible",
    mobile: 9876543215,
    gmail: "sarah.jones@gmail.com",
  },
  {
    username: "kevin_brown",
    image: "https://images.unsplash.com/photo-7",
    password: "Kevin@123",
    goals: ["Endurance Training"],
    preferences: ["Long-Distance Running", "Outdoor Cycling"],
    availability: "Weekends",
    mobile: 9876543216,
    gmail: "kevin.brown@gmail.com",
  },
];

module.exports = sampleRequestUsers;

module.exports = { requestUserData: sampleRequestUsers };
